/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#dded3a",
        "on-surface": "#111d21",
        "primary-fixed": "#a3eff7",
        "surface-bright": "#f1fbff",
        "inverse-primary": "#87d3da",
        "on-surface-variant": "#3f494a",
        "on-secondary": "#ffffff",
        "secondary": "#00696b",
        "tertiary": "#414700",
        "outline-variant": "#bec8c9",
        "tertiary-container": "#586000",
        "tertiary-fixed-dim": "#c1d015",
        "secondary-container": "#79f2f5",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#87d3da",
        "on-tertiary-fixed-variant": "#444b00",
        "surface-container-low": "#e9f6fb",
        "secondary-fixed": "#7cf5f8",
        "on-primary-fixed": "#002022",
        "on-primary-fixed-variant": "#004f55",
        "secondary-fixed-dim": "#5cd8db",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#006e70",
        "background": "#f1fbff",
        "primary": "#004b51",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#004f51",
        "surface-container": "#e3f0f5",
        "on-background": "#111d21",
        "inverse-on-surface": "#e6f3f8",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#002021",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#94dfe7",
        "surface": "#f1fbff",
        "outline": "#6f797a",
        "error-container": "#ffdad6",
        "primary-container": "#00656c",
        "surface-variant": "#d8e5ea",
        "on-tertiary-fixed": "#1a1d00",
        "surface-container-high": "#ddeaf0",
        "on-tertiary-container": "#cede28",
        "surface-tint": "#0a6970",
        "inverse-surface": "#263236",
        "surface-dim": "#cfdce1",
        "surface-container-highest": "#d8e5ea"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "space-lg": "2rem",
        "margin-lg": "4rem",
        "gutter-lg": "2.5rem",
        "space-md": "1.25rem",
        "gutter": "1.5rem",
        "space-sm": "0.75rem",
        "gutter-sm": "1rem",
        "margin-sm": "1rem",
        "space-xs": "0.375rem",
        "margin": "2rem",
        "space-xl": "3.5rem"
      },
      fontFamily: {
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md-mobile": ["Syne", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "display-xl": ["Syne", "sans-serif"],
        "headline-lg": ["Syne", "sans-serif"],
        "headline-lg-mobile": ["Syne", "sans-serif"],
        "headline-sm": ["Syne", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-xl-mobile": ["Syne", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Syne", "sans-serif"],
        "title-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "syne": ["Syne", "sans-serif"],
        "jakarta": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "label-lg": ["14px", { lineHeight: "18px", letterSpacing: "0.06em", fontWeight: "700" }],
        "headline-md-mobile": ["24px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "600" }],
        "display-xl": ["72px", { lineHeight: "76px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg": ["48px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "display-xl-mobile": ["44px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "title-md": ["17px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-lg": ["20px", { lineHeight: "26px", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      }
    }
  },
  plugins: []
};
